# Generated by Django 5.0.6 on 2024-07-01 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('percentage_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_description', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('performance_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.performancearea')),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.FloatField()),
                ('score_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.scorecriteria')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.department')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.appraisal')),
                ('backoffice_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scorecard.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='appraisal',
            name='frontend_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='scorecard.userprofile'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('industry', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('tax_identification_number', models.CharField(max_length=255)),
                ('years_in_business', models.IntegerField()),
                ('production_capacity', models.CharField(max_length=255)),
                ('product_types', models.CharField(max_length=255)),
                ('service_types', models.CharField(max_length=255)),
                ('frontend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='scorecard.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='appraisal',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.vendor'),
        ),
    ]
