# Generated by Django 5.0.6 on 2024-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_audittrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
