# Generated by Django 5.0.6 on 2024-07-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('scorecard', '0005_backofficeadmin_btsosadmin_frontofficeruser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
