# Generated by Django 5.0.6 on 2024-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0007_report_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
