# Generated by Django 5.0.6 on 2024-07-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0008_ratingscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='area_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='area_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='rating_scale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scorecard.ratingscale'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='wtd_rating',
            field=models.FloatField(default=0),
        ),
    ]
