# Generated by Django 5.0.6 on 2024-07-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0009_appraisal_area_rating_appraisal_area_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='rating_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.ratingscale'),
        ),
    ]
