# Generated by Django 5.0.6 on 2024-07-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0010_alter_appraisal_rating_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='rating_scale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scorecard.ratingscale'),
        ),
    ]
