# Generated by Django 5.0.6 on 2024-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0011_alter_appraisal_rating_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='area_rating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='area_weight',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='wtd_rating',
            field=models.FloatField(default=1),
        ),
    ]
