# Generated by Django 5.0.6 on 2024-07-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0012_alter_appraisal_area_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='area_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='area_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='rating_scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.ratingscale'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='wtd_rating',
            field=models.FloatField(null=True),
        ),
    ]
