# Generated by Django 5.0.6 on 2024-07-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0014_alter_appraisal_rating_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='area_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='area_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='rating_scale',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='scorecard.ratingscale'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='wtd_rating',
            field=models.FloatField(default=0),
        ),
    ]
