from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('vendors/', views.vendor_list, name='vendor_list'),
    path('vendors/create/', views.vendor_create, name='vendor_create'),
    path('vendors/edit/<int:pk>/', views.vendor_edit, name='vendor_edit'),
    path('vendors/delete/<int:pk>/', views.vendor_delete, name='vendor_delete'),
    path('performance_areas/', views.performance_area_list, name='performance_area_list'),
    path('performance_areas/create/', views.performance_area_create, name='performance_area_create'),
    path('performance_areas/edit/<int:pk>/', views.performance_area_edit, name='performance_area_edit'),
    path('performance_areas/delete/<int:pk>/', views.performance_area_delete, name='performance_area_delete'),
    path('score_criteria/', views.score_criteria_list, name='score_criteria_list'),
    path('score_criteria/create/', views.score_criteria_create, name='score_criteria_create'),
    path('score_criteria/edit/<int:pk>/', views.score_criteria_edit, name='score_criteria_edit'),
    path('score_criteria/delete/<int:pk>/', views.score_criteria_delete, name='score_criteria_delete'),
    path('appraisals/', views.appraisal_list, name='appraisal_list'),
    path('appraisals/create/', views.appraisal_create, name='appraisal_create'),
    path('appraisals/edit/<int:pk>/', views.appraisal_edit, name='appraisal_edit'),
    path('appraisals/delete/<int:pk>/', views.appraisal_delete, name='appraisal_delete'),
    path('reports/', views.report_list, name='report_list'),
    path('reports/create/', views.report_create, name='report_create'),
    path('reports/download_csv/', views.download_csv, name='download_csv'),
    path('reports/download_pdf/', views.download_pdf, name='download_pdf'),
    path('users/', views.user_list, name='user_list'),
    path('users/create/', views.user_create, name='user_create'),
    path('users/edit/<int:pk>/', views.user_edit, name='user_edit'),
    path('users/delete/<int:pk>/', views.user_delete, name='user_delete'),
    path('user_roles/', views.user_role_list, name='user_role_list'),
    path('user_roles/create/', views.user_role_create, name='user_role_create'),
    path('user_roles/edit/<int:pk>/', views.user_role_edit, name='user_role_edit'),
    path('user_roles/delete/<int:pk>/', views.user_role_delete, name='user_role_delete'),
    path('submit/', views.submit_scorecard, name='submit_scorecard'),
    path('scorecards/', views.scorecard_list, name='scorecard_list'),
    path('audit_reports/', views.audit_report_list, name='audit_report_list'),
    path('audit_reports/download_csv/', views.download_audit_csv, name='download_audit_csv'),
    path('audit_reports/download_pdf/', views.download_audit_pdf, name='download_audit_pdf'),
    path('rating_scales/', views.rating_scale_list, name='rating_scale_list'),
    path('rating_scales/create/', views.rating_scale_create, name='rating_scale_create'),
    path('rating_scales/<int:pk>/edit/', views.rating_scale_edit, name='rating_scale_edit'),
    path('rating_scales/<int:pk>/delete/', views.rating_scale_delete, name='rating_scale_delete'),
]
